version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/testdb
    ports:
      - "8000:80"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork: