name: Docker Image Deploy

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up date tag
      id: date_tag
      run: echo "DATE_TAG=$(date +%d-%m-%H.%M)" >> $GITHUB_ENV
      
    - name: Login into Dockerhub
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USR }}" --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vitortoniolo/crud_db_2:latest

    - name: Push image to Dockerhub
      run: |
        docker push vitortoniolo/crud_db_2:${{ env.DATE_TAG }}
      
    
    
